import { DEFAULT_SHORT_URL_LENGTH, PASSWORD_MIN_LENGTH } from "./Definitions";

export const LINKS = {
  VALIDATION_MESSAGES: {
    DEFINED_SHORT_URL_LENGTH: `Short URL must be exactly ${DEFAULT_SHORT_URL_LENGTH} characters`,
    SHORT_URL_PATTERN: "Short URL must be a valid string",
  },
  ERROR_MESSAGES: {
    DATABASE_ERROR_LINKS: "DATABASE_ERROR_LINKS",
    SERVICE_ERROR_LINKS: "SERVICE_ERROR_LINKS",
  },
  ERROR_CODES: {
    DATABASE_ERROR_GET_FIRST_LINK: "DATABASE_ERROR_GET_FIRST_LINK",
    DATABASE_ERROR_ADD_ONE_LINK: "DATABASE_ERROR_ADD_ONE_LINK",
    URL_FOR_CONVERTING_NOT_PROVIDED: "URL_FOR_CONVERTING_NOT_PROVIDED",
    UNKNOWN_SERVICE_ERROR_FOR_CREATING_SHORT_URL:
      "UNKNOWN_SERVICE_ERROR_FOR_CREATING_SHORT_URL",
    UNKNOWN_ROUTE_ERROR_FOR_CREATING_SHORT_URL:
      "UNKNOWN_ROUTE_ERROR_FOR_CREATING_SHORT_URL",
    SHORT_URL_FOR_REDIRECTING_NOT_PROVIDED:
      "SHORT_URL_FOR_REDIRECTING_NOT_PROVIDED",
    SHORT_URL_FOR_REDIRECTING_NOT_FOUND_IN_DATABASE:
      "SHORT_URL_FOR_REDIRECTING_NOT_FOUND_IN_DATABASE",
    UNKNOWN_SERVICE_ERROR_FOR_REDIRECTING_TO_URL:
      "UNKNOWN_SERVICE_ERROR_FOR_REDIRECTING_TO_URL",
    UNKNOWN_ROUTE_ERROR_FOR_REDIRECTING_TO_URL:
      "UNKNOWN_ROUTE_ERROR_FOR_REDIRECTING_TO_URL",
  },
};

export const USERS = {
  VALIDATION_MESSAGES: {
    PASSWORD_MIN_LENGTH_REQUIREMENT: `Password must be ${PASSWORD_MIN_LENGTH} characters length`,
    PASSWORD_PATTERN:
      "Password must contain at least one upper letter, at least one lower letter, at least one number",
  },
  ERROR_MESSAGES: {
    DATABASE_ERROR_USERS: "DATABASE_ERROR_USERS",
    SERVICE_ERROR_USERS: "SERVICE_ERROR_USERS",
  },
  ERROR_CODES: {
    DATABASE_ERROR_GET_FIRST_USER: "DATABASE_ERROR_GET_FIRST_USER",
    DATABASE_ERROR_CREATE_USER: "DATABASE_ERROR_CREATE_USER",
    UNKNOWN_SERVICE_ERROR_FOR_CREATING_USER:
      "UNKNOWN_SERVICE_ERROR_FOR_CREATING_USER",
    USER_WITH_EMAIL_ALREADY_EXISTS: "USER_WITH_EMAIL_ALREADY_EXISTS",
    UNKNOWN_ROUTE_ERROR_FOR_CREATING_USER:
      "UNKNOWN_ROUTE_ERROR_FOR_CREATING_USER",
  },
};

export const ENCRYPTION = {
  ERROR_MESSAGES: {
    ERROR_ENCRYPTION: "ERROR_ENCRYPTION",
  },
  ERROR_CODES: {
    ERROR_HASHING_STRING: "ERROR_HASHING_STRING",
    ERROR_COMPARING_HASH: "ERROR_COMPARING_HASH",
  },
};

export const DEFAULT_ERROR_MESSAGE = "Something went wrong";
